src/objects/Clan__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>Clan</label>
    <nameField>
        <label>Clan Tag</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Clan_Game__c.object
<CustomObject>
    <description>A record for tracking overall points earned for the linked clan&apos;s clan games event</description>
    <fields>
        <fullName>Clan_Games_Event__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Clan Games Event</label>
        <referenceTo>Clan_Games_Event__c</referenceTo>
        <relationshipLabel>Clan Games</relationshipLabel>
        <relationshipName>Clan_Games</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Clan__c</fullName>
        <label>Clan</label>
        <referenceTo>Clan__c</referenceTo>
        <relationshipLabel>Clan Games</relationshipLabel>
        <relationshipName>Clan_Games</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Clan Game</label>
    <nameField>
        <displayFormat>CG-{0000}</displayFormat>
        <label>Clan Games Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clan Games</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Clan_Game_Contribution__c.object
<CustomObject>
    <fields>
        <fullName>Clan_Game__c</fullName>
        <label>Clan Game</label>
        <referenceTo>Clan_Game__c</referenceTo>
        <relationshipLabel>Clan Games Contributions</relationshipLabel>
        <relationshipName>Clan_Games_Contributions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Player__c</fullName>
        <label>Player</label>
        <referenceTo>Player__c</referenceTo>
        <relationshipLabel>Clan Games Contributions</relationshipLabel>
        <relationshipName>Clan_Games_Contributions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Total_Clan_Games_Points_at_end__c</fullName>
        <label>Total Clan Games Points at end</label>
        <precision>8</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Clan_Games_Points_at_start__c</fullName>
        <label>Total Clan Games Points at start</label>
        <precision>8</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Clan Game Contribution</label>
    <nameField>
        <displayFormat>CGC-{00000}</displayFormat>
        <label>Clan Game Contribution Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clan Games Contributions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Clan_Games_Event__c.object
<CustomObject>
    <fields>
        <fullName>Date_End__c</fullName>
        <description>Date the clan games ends/ended</description>
        <inlineHelpText>Date the clan games ends/ended</inlineHelpText>
        <label>Date End</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_Start__c</fullName>
        <description>Date the clan games event started</description>
        <label>Date Start</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Clan Games Event</label>
    <nameField>
        <displayFormat>CGE-{0000}</displayFormat>
        <label>Clan Games Event Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clan Game Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Clan_Member_Session__c.object
<CustomObject>
    <fields>
        <fullName>Clan__c</fullName>
        <label>Clan</label>
        <referenceTo>Clan__c</referenceTo>
        <relationshipLabel>Clan Member Sessions</relationshipLabel>
        <relationshipName>Clan_Member_Sessions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date_Time_End__c</fullName>
        <label>Date End</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Date_Time_Start__c</fullName>
        <label>Date Start</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Player__c</fullName>
        <label>Player</label>
        <referenceTo>Player__c</referenceTo>
        <relationshipLabel>Clan Member Sessions</relationshipLabel>
        <relationshipName>Clan_Member_Sessions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Clan Member Session</label>
    <nameField>
        <displayFormat>CMS-{000000}</displayFormat>
        <label>Clan Member Session Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clan Member Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Player__c.object
<CustomObject>
    <fields>
        <fullName>Current_Clan_Member_Session__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Current Clan Session</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>This Clan session does not belong to this player</errorMessage>
            <filterItems>
                <field>Clan_Member_Session__c.Player__r.Id</field>
                <operation>equals</operation>
                <valueField>$Source.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Clan_Member_Session__c</referenceTo>
        <relationshipLabel>Players</relationshipLabel>
        <relationshipName>Players</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>32</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Clan_Games_Points__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Clan Games Points</label>
        <precision>8</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Player</label>
    <nameField>
        <label>Player Tag</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PlayerTriggerHelper.cls
public class PlayerTriggerHelper {

    private String clanTag;
    private List<Player__c> newPlayerInfo;
    private List<Player__c> oldPlayerInfo;
    private Clan_Game__c currentClanGame;
    
    public PlayerTriggerHelper(String clanTag, List<Player__c> players){
        Initialize(clanTag, Players);
    }

    public PlayerTriggerHelper Initialize(String clanTag, List<Player__c> players){
        this.clanTag = clanTag;
        this.newPlayerInfo = GiveNewPlayerInfoOrgIds(players);
        this.oldPlayerInfo = PlayerCollectionsHelper.FindClanPlayerInfo(this.clanTag);
        this.currentClanGame = FindCurrentClanGame();
        return this;
    }
    
    private List<Player__c> GiveNewPlayerInfoOrgIds(List<player__c> players){
        Map<String, Player__c> playerMapByTag = PlayerCollectionsHelper.MapPlayersByTag(players);        
        List<Player__c> orgPlayers = [SELECT Id, Name, Name__c, Current_Clan_Member_Session__c, Total_Clan_Games_Points__c FROM Player__c WHERE name IN :playerMapByTag.keyset()]; 
        for (Player__c existingPlayer : orgPlayers){
            playerMapByTag.get(existingPlayer.name).id = existingPlayer.id;
        }        
        return playerMapByTag.values();
    }
    
    private Clan_Game__c FindCurrentClanGame(){
        List<Clan_Game__c> ccg = [
            SELECT id FROM Clan_Game__c 
            WHERE Clan_Games_Event__r.Date_Start__c <= :Utilities.currentDate 
            AND Clan_Games_Event__r.Date_End__c >= :Utilities.currentDate 
            AND Clan__r.name = :clanTag
            LIMIT 1];
        return (ccg.size() > 0) ? ccg[0] : null;
    }
    
    public void HandleNewPlayerInfo() {        
        HandleAddingUpdatingPlayers();			
        HandleClanMemberSessions();
        HandleClanGameContributions();
        HandlePlayersLeaving();
    }
    
	private void HandleAddingUpdatingPlayers(){
       	upsert this.newPlayerInfo;
    }
    
    private void HandleClanMemberSessions(){
        Map<id, Player__c> playersRequiringSession = new map<id, Player__c>(FindNewPlayers());
        If (playersRequiringSession.values().size() > 0){
            List<Clan_Member_Session__c> cmsData = InsertClanMemberSessions();//TODO FIX: violates query action rule
            UpdatePlayersCurrentMemberSessionsWith(cmsData);
        }
    }
    
    //TODO: try optimising this function with oldplayerinfo instead of using the query
    private List<Player__c> FindNewPlayers(){
        Set<id> playerIds = new Map<Id, Player__c>(this.newPlayerInfo).keyset();        
        List<Player__c> newPlayers = [
            SELECT Id, Name, Name__c, Total_Clan_Games_Points__c 
            FROM Player__c 
            WHERE (id IN :playerIds) 
            AND (NOT(Current_Clan_Member_Session__r.Clan__r.name = :clanTag))
        ];
        return newPlayers;
    }
    
    private List<Clan_Member_Session__c> InsertClanMemberSessions() {//violates query command principle
        Id clanId = [SELECT Id FROM Clan__c WHERE name = :clanTag][0].id;
        List<Clan_Member_Session__c> cmsData = new List<Clan_Member_Session__c>();
        for (Player__c playerRequiringSession : FindNewPlayers()){    
            cmsData.add(new Clan_Member_Session__c(
                Date_Time_Start__c = Utilities.now,
                Date_Time_End__c = Utilities.now,
                Player__c = playerRequiringSession.id,
                Clan__c = clanId
            ));
        }
        insert cmsData;
        return cmsData;
    }
    
    private void UpdatePlayersCurrentMemberSessionsWith(List<Clan_Member_Session__c> cmsData){
        Map<id, Clan_Member_Session__c> cmsByPlayerIdMap = new Map<id, Clan_Member_Session__c>();	
        for (Clan_Member_Session__c cms : cmsData) {
            cmsByPlayerIdMap.put(cms.Player__c, cms);
        }
        
        Map<id, Player__c> playersRequiringSession = new map<id, Player__c>(FindNewPlayers());
        for (Player__c player : this.newPlayerInfo) {
            if (playersRequiringSession.keyset().contains(player.Id)) {
                player.Current_Clan_Member_Session__c = cmsByPlayerIdMap.get(player.id).id;
            }
        }
        update this.newPlayerInfo;        
    }
    
    private void HandleClanGameContributions(){        
        if (isClanGameRunning()) {
            List<Clan_Game_Contribution__c> clanGameContributionsToUpsert = new List<Clan_Game_Contribution__c>();            
            
            Map<id, Player__c> continuingPlayers = getContinuingPlayers();            
            Map<id, Clan_Game_Contribution__c> existingClanGameContributions = FindExistingClanGameContributions();
            Map<String, Clan_Game_Contribution__c> contributionsByPlayerTag = PlayerCollectionsHelper.MapContributionsByPlayerTag(this.newPlayerInfo, existingClanGameContributions.values());

            Map<id, Player__c> oldPlayerInfoIdMap = new Map<id, Player__c>(this.oldPlayerInfo);
            for (Player__c player : this.newPlayerInfo) {
                Clan_Game_Contribution__c cgcToAdd = new Clan_Game_Contribution__c();
                    
                if (contributionsByPlayerTag.get(player.name) != null) { //if player already has a contribution
                    contributionsByPlayerTag.get(player.name).Total_Clan_Games_Points_at_end__c	= player.Total_Clan_Games_Points__c;
                    clanGameContributionsToUpsert.add(contributionsByPlayerTag.get(player.name));
                } else if (continuingPlayers.get(player.id) != null) { //if player does not have a contribution but is a continuing member...
                    clanGameContributionsToUpsert.add(new Clan_Game_Contribution__c(
                        Player__c							= player.id,
                        Clan_Game__c						= this.currentClanGame.id,
                        Total_Clan_Games_Points_at_start__c	= oldPlayerInfoIdMap.get(player.Id).Total_Clan_Games_Points__c,
                        Total_Clan_Games_Points_at_end__c	= player.Total_Clan_Games_Points__c
                    ));	
                } else {												//otherwise if the player is new...
                    clanGameContributionsToUpsert.add(new Clan_Game_Contribution__c(
                        Player__c							= player.id,
                        Clan_Game__c						= this.currentClanGame.id,
                        Total_Clan_Games_Points_at_start__c	= player.Total_Clan_Games_Points__c,
                        Total_Clan_Games_Points_at_end__c	= player.Total_Clan_Games_Points__c
                    ));	
                }
            }             
            upsert clanGameContributionsToUpsert;
        }
    }
    
    private boolean isClanGameRunning(){
        return (currentClanGame != Null);
    }
    
    private Map<Id, Player__c> getContinuingPlayers(){        
        Map<Id, Player__c> oldPlayerInfoIdMap = new Map<Id, Player__c>(this.oldPlayerInfo);
        Map<Id, Player__c> newPlayerInfoIdMap = new Map<Id, Player__c>(this.newPlayerInfo);
        Map<Id, Player__c> continuingPlayers = new Map<Id, Player__c>();
        for (Player__c newPlayer : this.newPlayerInfo) {
            if (oldPlayerInfoIdMap.get(newPlayer.id) != null){
                continuingPlayers.put(newPlayer.id, newPlayerInfoIdMap.get(newPlayer.id));
            }
        }
        return continuingPlayers;
    }
    
    private void HandlePlayersLeaving(){
        Map<id, player__c> newPlayerDataMap = new Map<id, player__c>(this.newPlayerInfo);		//get all players currently in the clan (from request)
        Map<id, Player__c> orgPlayers = FindOrgPlayersByClanTag(this.clanTag);						//get all of the players currently in the database
        
        List<player__c> absentPlayers = [SELECT id, current_clan_member_session__c FROM player__c WHERE (id IN :orgPlayers.keyset()) AND (NOT(id IN :newPlayerDataMap.keyset()))];
        if(absentPlayers.size() > 0){														//if there are members no longer in the clan...
            List<id> cmsIds = new List<id>();													//make a store to collect CMS ids
            for (Player__c player : absentPlayers) {											//for every absent clan member...
                cmsIds.add(player.Current_Clan_Member_Session__c);									//get all of these players current clan member sessions and set their end date to now.
                player.current_clan_member_session__c = null;										//set their current clan member session to null
            }
            update absentPlayers;															//unlink all the players from their previous clan member sessions
            
            //update the clan member sessions final time
            List<Clan_member_session__c> cmsList = [SELECT id, Date_Time_End__c FROM Clan_Member_Session__c WHERE id IN :cmsIds];
            for (clan_member_session__c cmsItem : cmsList){
                cmsItem.Date_Time_End__c = Utilities.now;
            }
            update cmsList;
        }
    }
    
    //------------------------------Helpers------------------------------//

    private Map<id, Clan_Game_Contribution__c> FindExistingClanGameContributions(){
        Map<id, Clan_Game_Contribution__c> cgc = new Map<id, Clan_Game_Contribution__c>([
                SELECT id, player__c 
                FROM Clan_Game_Contribution__c 
                WHERE Clan_Game__c = :currentClanGame.id AND Player__c IN :getContinuingPlayers().values()
            ]);
        return cgc;
    }
    
    private Map<Id, Player__c> FindOrgPlayersByClanTag(String clanTag){
        Map<id, Clan_Member_session__c> cmsData = new Map<Id, clan_member_session__c>([SELECT id FROM clan_member_session__c WHERE (clan__r.name = :clanTag) AND (player__r.Current_clan_member_session__c != null)]);
		Map<id, Player__c> players = new Map<Id, Player__c>([SELECT Id, name, name__c, total_clan_games_points__c, current_clan_member_session__c FROM Player__c WHERE current_clan_member_session__c IN :cmsData.keyset()]);
        return players;
    }

}