src/objects/Clan__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>Clan</label>
    <nameField>
        <label>Clan Tag</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Clan_Game__c.object
<CustomObject>
    <description>A record for tracking overall points earned for the linked clan&apos;s clan games event</description>
    <fields>
        <fullName>Clan_Games_Event__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Clan Games Event</label>
        <referenceTo>Clan_Games_Event__c</referenceTo>
        <relationshipLabel>Clan Games</relationshipLabel>
        <relationshipName>Clan_Games</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Clan__c</fullName>
        <label>Clan</label>
        <referenceTo>Clan__c</referenceTo>
        <relationshipLabel>Clan Games</relationshipLabel>
        <relationshipName>Clan_Games</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Clan Game</label>
    <nameField>
        <displayFormat>CG-{0000}</displayFormat>
        <label>Clan Games Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clan Games</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Clan_Game_Contribution__c.object
<CustomObject>
    <fields>
        <fullName>Clan_Game__c</fullName>
        <label>Clan Game</label>
        <referenceTo>Clan_Game__c</referenceTo>
        <relationshipLabel>Clan Games Contributions</relationshipLabel>
        <relationshipName>Clan_Games_Contributions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Player__c</fullName>
        <label>Player</label>
        <referenceTo>Player__c</referenceTo>
        <relationshipLabel>Clan Games Contributions</relationshipLabel>
        <relationshipName>Clan_Games_Contributions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Total_Clan_Games_Points_at_end__c</fullName>
        <label>Total Clan Games Points at end</label>
        <precision>8</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Clan_Games_Points_at_start__c</fullName>
        <label>Total Clan Games Points at start</label>
        <precision>8</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Clan Game Contribution</label>
    <nameField>
        <displayFormat>CGC-{00000}</displayFormat>
        <label>Clan Game Contribution Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clan Games Contributions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Clan_Games_Event__c.object
<CustomObject>
    <fields>
        <fullName>Date_End__c</fullName>
        <description>Date the clan games ends/ended</description>
        <inlineHelpText>Date the clan games ends/ended</inlineHelpText>
        <label>Date End</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_Start__c</fullName>
        <description>Date the clan games event started</description>
        <label>Date Start</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Clan Games Event</label>
    <nameField>
        <displayFormat>CGE-{0000}</displayFormat>
        <label>Clan Games Event Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clan Game Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Player__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>32</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Clan_Games_Points__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Clan Games Points</label>
        <precision>8</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Player</label>
    <nameField>
        <label>Player Tag</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ClashDataManagerTest.cls
@IsTest
public class ClashDataManagerTest {
    
    @istest static void T01_ClanNotDuplicatedOnSync(){
        Clan__c clanData = new Clan__c(name = TestData.CLAN_TAG_1, name__c='Max Clan Games');
        insert clanData.clone();
                
        Test.startTest();
            ClashDataManager.HandleNewClanInfo(clanData.clone());
        Test.stopTest();
        
        List<Clan__c> orgClans = [SELECT Id, Name, Name__c FROM Clan__c];
        
        System.assertEquals(1, orgClans.size());
        System.assertEquals('Max Clan Games', orgClans[0].Name__c);        
    }
        
    //========================CLAN GAMES FUNCTIONALITY=========================//
    
    @istest static void T07_CreateClanGameOnClanGameEventStart(){
        //<setup>//
        //set time to clan games
        Utilities.today = Date.newInstance(2019, 1, 1);																			//set now utility to a time in between those dates
        Utilities.now   = Date.newInstance(2019, 1, 1);
        insert new Clan_Games_Event__c(Date_Start__c=Date.newInstance(2020, 1, 1), Date_End__c=Date.newInstance(2020, 1, 7));	//new clan game event with start and end dates
		insert TestData.CLAN_1.clone();
        
        List<player__c> players = new List<Player__c>();
        Player__c player1 = new Player__c(Name='#P0UUCUYCP', Name__c='Addidy', Total_Clan_Games_Points__c=1000);					//set up player data
        Player__c player2 = new Player__c(Name='#YYU2UVGV0', Name__c='Syntax', Total_Clan_Games_Points__c=500);
        players.add(player1.clone());
        players.add(player2.clone());
        //</SETUP>//
        
        Test.startTest();
        	//--------------------------------------Sync clan data before clan games event starts------------------------------------------//
        	ClashDataManager.SyncAllClashData();	
        	new PlayerTriggerHelper(TestData.CLAN_TAG_1, players).HandleNewPlayerInfo();
        	
        	//collect data
        	List<Clan_Game__c> 				resultClanGames 			= [SELECT Id, Clan__c, Clan_Games_Event__c FROM Clan_Game__c];
        	//verify results
        	System.assertEquals(0, resultClanGames.size(), 				'Clan Game was not created');
        
        	//-------------------------------Sync clan data after clan games event starts for the first time-------------------------------//
			//<SETUP>//
        	//set time to clan games start
        	Utilities.today = Date.newInstance(2020, 1, 1);																			//set now utility to a time in between those dates
        	Utilities.now   = Date.newInstance(2020, 1, 1);
        	//reset player references
        	players.clear();
        	players.add(player1.clone());
        	players.add(player2.clone());
        	//have the second player accumulate some points since last sync
        	players[1].Total_Clan_Games_Points__c = 1200;
        	//</SETUP>//
        
        	//<TEST>//
        	ClashDataManager.SyncAllClashData();
        	new PlayerTriggerHelper(TestData.CLAN_TAG_1, players).HandleNewPlayerInfo();
        	//</TEST>//
        	
            //<collect result data>//
                                            resultClanGames 				= [SELECT Id, Clan__c, Clan_Games_Event__c FROM Clan_Game__c];
            List<Clan_Game_Contribution__c> resultClanGameContributions 	= [SELECT Id, player__c, Total_Clan_Games_Points_at_start__c, Total_Clan_Games_Points_at_end__c FROM Clan_Game_Contribution__c];
            List<Player__c> 				resultPlayers					= [SELECT Id, name, name__c FROM Player__c];
            
            Map<String, Clan_Game_Contribution__c> resultContributionsByPlayerTag = PlayerCollectionsHelper.MapContributionsByPlayerTag(resultPlayers, resultClanGameContributions);
            //</collect result data>//
            
            //<VERIFY EXPECTED RESULTS>
            System.assertEquals(1, resultClanGames.size(), 'Clan Game was not created');
        	//</VERIFY EXPECTED RESULTS>//
        	
        	
        	//--------------------------------------------------sync after clan games ends-----------------------------------------//
        	//--------------------------------------------------another clan game begins-------------------------------------------//
        Test.stopTest();
    }
}