src/objects/Clan__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>Clan</label>
    <nameField>
        <label>Clan Tag</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Clan_Game__c.object
<CustomObject>
    <description>A record for tracking overall points earned for the linked clan&apos;s clan games event</description>
    <fields>
        <fullName>Clan_Games_Event__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Clan Games Event</label>
        <referenceTo>Clan_Games_Event__c</referenceTo>
        <relationshipLabel>Clan Games</relationshipLabel>
        <relationshipName>Clan_Games</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Clan__c</fullName>
        <label>Clan</label>
        <referenceTo>Clan__c</referenceTo>
        <relationshipLabel>Clan Games</relationshipLabel>
        <relationshipName>Clan_Games</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Clan Game</label>
    <nameField>
        <displayFormat>CG-{0000}</displayFormat>
        <label>Clan Games Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clan Games</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Clan_Game_Contribution__c.object
<CustomObject>
    <fields>
        <fullName>Clan_Game__c</fullName>
        <label>Clan Game</label>
        <referenceTo>Clan_Game__c</referenceTo>
        <relationshipLabel>Clan Games Contributions</relationshipLabel>
        <relationshipName>Clan_Games_Contributions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Player__c</fullName>
        <label>Player</label>
        <referenceTo>Player__c</referenceTo>
        <relationshipLabel>Clan Games Contributions</relationshipLabel>
        <relationshipName>Clan_Games_Contributions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Total_Clan_Games_Points_at_end__c</fullName>
        <label>Total Clan Games Points at end</label>
        <precision>8</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Clan_Games_Points_at_start__c</fullName>
        <label>Total Clan Games Points at start</label>
        <precision>8</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Clan Game Contribution</label>
    <nameField>
        <displayFormat>CGC-{00000}</displayFormat>
        <label>Clan Game Contribution Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clan Games Contributions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Clan_Games_Event__c.object
<CustomObject>
    <fields>
        <fullName>Date_End__c</fullName>
        <description>Date the clan games ends/ended</description>
        <inlineHelpText>Date the clan games ends/ended</inlineHelpText>
        <label>Date End</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_Start__c</fullName>
        <description>Date the clan games event started</description>
        <label>Date Start</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Clan Games Event</label>
    <nameField>
        <displayFormat>CGE-{0000}</displayFormat>
        <label>Clan Games Event Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clan Game Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Clan_Member_Session__c.object
<CustomObject>
    <fields>
        <fullName>Clan__c</fullName>
        <label>Clan</label>
        <referenceTo>Clan__c</referenceTo>
        <relationshipLabel>Clan Member Sessions</relationshipLabel>
        <relationshipName>Clan_Member_Sessions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date_Time_End__c</fullName>
        <label>Date End</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Date_Time_Start__c</fullName>
        <label>Date Start</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Player__c</fullName>
        <label>Player</label>
        <referenceTo>Player__c</referenceTo>
        <relationshipLabel>Clan Member Sessions</relationshipLabel>
        <relationshipName>Clan_Member_Sessions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Clan Member Session</label>
    <nameField>
        <displayFormat>CMS-{000000}</displayFormat>
        <label>Clan Member Session Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clan Member Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Player__c.object
<CustomObject>
    <fields>
        <fullName>Current_Clan_Member_Session__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Current Clan Session</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>This Clan session does not belong to this player</errorMessage>
            <filterItems>
                <field>Clan_Member_Session__c.Player__r.Id</field>
                <operation>equals</operation>
                <valueField>$Source.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Clan_Member_Session__c</referenceTo>
        <relationshipLabel>Players</relationshipLabel>
        <relationshipName>Players</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>32</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Clan_Games_Points__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Clan Games Points</label>
        <precision>8</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Player</label>
    <nameField>
        <label>Player Tag</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ClashOverview.cls
/* This class is intended to collect data from the org relevant to cgt
 * in order to verify unit tests.*/

public class ClashOverview {
	private static List<Player__c> 				allPlayers;
    private static List<Clan__c> 				allClans;
    private static List<Clan_Games_Event__c> 	allClanGamesEvents;
    
    private static List<Clan_game__c> 				allClanGames;
    private static List<Clan_Game_Contribution__c> 	allClanGameContributions;  
    private static List<Clan_Member_Session__c> 	allClanMemberSessions;
    
    public static void Sync(){
        allPlayers 					= [SELECT id, name, name__c, current_clan_member_session__c, Total_clan_games_points__c FROM Player__c];
        allClans 					= [SELECT id, name, name__c FROM Clan__c];
        allClanGamesEvents 			= [SELECT id, date_start__c, date_end__c FROM Clan_Games_Event__c];
        allClanGames 				= [SELECT id, clan__c, clan_games_event__c FROM Clan_game__c];
        allClanGameContributions 	= [SELECT id, clan_game__c, player__c, total_clan_games_points_at_start__c, total_clan_games_points_at_end__c FROM Clan_Game_Contribution__c];
        allClanMemberSessions 		= [SELECT id, clan__c, player__c, date_time_start__c, date_time_end__c FROM Clan_Member_Session__c];        
    }
    
    public static List<Player__c> 			getAllPlayers(){
        return allPlayers;
    }
    public static List<Clan__c> 			getAllClans(){
        return allClans;
    }
    public static List<Clan_Games_Event__c> getAllClanGamesEvents(){
        return allClanGamesEvents;
    }
    public static List<Clan_game__c> 		getAllClanGames(){
        return allClanGames;
    }
    public static List<Clan_Game_Contribution__c> 	getAllClanGameContributions(){
        return allClanGameContributions;
    }
    public static List<Clan_Member_Session__c> 		getAllClanMemberSessions(){
        return allClanMemberSessions;
    }
    
    public static integer getClanCount(){
        return allClans.size();
    }    
    public static integer getPlayerCount(){
        return allPlayers.size();
    }    
    public static integer getClanMemberSessionsCount(){
        return allClanMemberSessions.size();
    }    
    public static integer getClanGameContribtutionsCount(){
        return allClanGameContributions.size();
    }
    
    public static Map<String, Player__c> getPlayerMapByName(){
        return PlayerCollectionsHelper.MapPlayersByName(allPlayers);
    }    
    public static Map<String, Player__c> getPlayerMapByTag(){
        return PlayerCollectionsHelper.MapPlayersByTag(allPlayers);
    }    
    public static Map<id, Player__c> getPlayerMap(){
        return PlayerCollectionsHelper.MapPlayersById(allPlayers);
    }
    //TODO finish.
}