src/objects/Clan__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>Clan</label>
    <nameField>
        <label>Clan Tag</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Player__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>32</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Clan_Games_Points__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Clan Games Points</label>
        <precision>8</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Player</label>
    <nameField>
        <label>Player Tag</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/QA_ClashPlayerDataSynchroniserTest.cls
@IsTest
public class QA_ClashPlayerDataSynchroniserTest {
	    @istest static void T01_InsertsPlayerData(){        
        Test.setMock(HttpCalloutMock.class, TestData.GenerateClashDataMock());
        List<player__c> players = new List<Player__c>();
        
        insert new Clan__c(name = TestData.CLAN_TAG_1, name__c = 'Max Clan Games');        
        players.add(new Player__c(Name=TestData.PLAYER_TAG_1, Name__c='Addidy', Total_Clan_Games_Points__c=0));
        players.add(new Player__c(Name=TestData.PLAYER_TAG_2, Name__c='Syntax', Total_Clan_Games_Points__c=0));
        
        QA_ClashPlayerDataSynchroniser cpds = new QA_ClashPlayerDataSynchroniser(TestData.CLAN_TAG_1, players);        
        Test.startTest();            
            System.enqueueJob(cpds);            
        Test.stopTest();
        
        List<player__c> orgPlayers = [SELECT Id, Name, Name__c, Total_Clan_Games_Points__c FROM Player__c];
        
        System.assertEquals(2, orgPlayers.size());
        System.assertEquals('Addidy', orgPlayers[0].Name__c);
        System.assert(orgPlayers[0].Total_Clan_Games_Points__c > 0);
    }
}