src/objects/Clan__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>Clan</label>
    <nameField>
        <label>Clan Tag</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/QA_ClashDataSynchroniserTest.cls
@IsTest
public class QA_ClashDataSynchroniserTest {
	@istest static void T01_InsertsClanData(){
        Test.setMock(HttpCalloutMock.class, TestData.GenerateClashDataMock()); 
        
        QA_ClashDataSynchroniser cds = new QA_ClashDataSynchroniser(TestData.CLAN_TAG_1);        
        Test.startTest();            
            System.enqueueJob(cds);            
        Test.stopTest();
        
        List<Clan__c> orgClans = [SELECT Id, Name, Name__c FROM Clan__c];
        
        System.assertEquals(1, orgClans.size());
        System.assertEquals('Max Clan Games', orgClans[0].Name__c);        
    }
}