src/objects/Clan__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>Clan</label>
    <nameField>
        <label>Clan Tag</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Clan_Game__c.object
<CustomObject>
    <description>A record for tracking overall points earned for the linked clan&apos;s clan games event</description>
    <fields>
        <fullName>Clan_Games_Event__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Clan Games Event</label>
        <referenceTo>Clan_Games_Event__c</referenceTo>
        <relationshipLabel>Clan Games</relationshipLabel>
        <relationshipName>Clan_Games</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Clan__c</fullName>
        <label>Clan</label>
        <referenceTo>Clan__c</referenceTo>
        <relationshipLabel>Clan Games</relationshipLabel>
        <relationshipName>Clan_Games</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Clan Game</label>
    <nameField>
        <displayFormat>CG-{0000}</displayFormat>
        <label>Clan Games Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clan Games</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Clan_Games_Event__c.object
<CustomObject>
    <fields>
        <fullName>Date_End__c</fullName>
        <description>Date the clan games ends/ended</description>
        <inlineHelpText>Date the clan games ends/ended</inlineHelpText>
        <label>Date End</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_Start__c</fullName>
        <description>Date the clan games event started</description>
        <label>Date Start</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Clan Games Event</label>
    <nameField>
        <displayFormat>CGE-{0000}</displayFormat>
        <label>Clan Games Event Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clan Game Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ClashDataManager.cls
public class ClashDataManager implements schedulable {
    /*
     * TODO: (refactorisation)
     * Split the logic in this class into PlayerTriggerHandler & ClanTriggerHandler.
     * (do this first) Reduce the number of arguments needed in functions by turning statics into instantiable classes with member variables
     * 
     */   
    public void Execute(System.SchedulableContext sc) {
        SyncAllClashData();
    }
    
    @InvocableMethod(label='Sync all Clash Data')
    public static void SyncAllClashData(){
        system.debug('Sync all clash data');
        List<Clan__c> clans = [SELECT id, name FROM Clan__c];       //get all the orgs clan's
        
        //deal with clan games events
        List<Clan_Games_Event__c> currentClanGamesEvent = [SELECT id, Date_Start__c, Date_End__c FROM Clan_Games_Event__c WHERE Date_Start__c <= :Utilities.currentDate AND Date_End__c >= :Utilities.currentDate];
        
        if (currentClanGamesEvent.size() > 0){                                                                      //if a clan games event is running/has started...
            //TODO Change this to support a clan being tracked during a clan game
            if([SELECT Id FROM Clan_Game__c].size() == 0){            
                List<Clan_Game__c> newClanGames = new List<Clan_Game__c>();
                for (Clan__c clan : clans)  {                                                                           //for every clan in the org...
                    newClanGames.add(new Clan_Game__c(Clan__c=clan.Id, Clan_Games_Event__c=currentClanGamesEvent[0].Id));                   //insert a clan game record for that clan
                }
                insert newClanGames;
            }
        }
        
        //sync all new clan information
        if (!Test.isRunningTest()) {                                                                            //if we are not running tests...
            for (Clan__c clan : clans)  {
                SyncClanAndMemberInfo(clan.Name);                                                                       //sync clan and member info (using callouts)
            }
        }
    }
    
    public static void SyncClanAndMemberInfo(String clanTag){               //Makes a web service callout chain to get specified clan info and subsequent player information that will sync the information to the org
        QA_ClashDataSynchroniser cds = new QA_ClashDataSynchroniser(clanTag);
        System.enqueueJob(cds);
    }
    
    public static void HandleNewClanInfo(Clan__c clan) {
        //TODO bulkify to handle list of clans in a seperate function
        List<Clan__c> orgClan = [SELECT Id, Name, Name__c FROM Clan__c WHERE name = :clan.Name];
        if (orgClan.size() > 0) {
            clan.id = orgClan[0].id;
        }
        upsert clan;
    }
}