src/objects/Clan__c.object
<CustomObject>
    <label>Clan</label>
    <nameField>
        <label>Clan Tag</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Clan_Game_Contribution__c.object
<CustomObject>
    <fields>
        <fullName>Player__c</fullName>
        <label>Player</label>
        <referenceTo>Player__c</referenceTo>
        <relationshipLabel>Clan Games Contributions</relationshipLabel>
        <relationshipName>Clan_Games_Contributions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Clan Game Contribution</label>
    <nameField>
        <displayFormat>CGC-{00000}</displayFormat>
        <label>Clan Game Contribution Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clan Games Contributions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Clan_Member_Session__c.object
<CustomObject>
    <fields>
        <fullName>Clan__c</fullName>
        <label>Clan</label>
        <referenceTo>Clan__c</referenceTo>
        <relationshipLabel>Clan Member Sessions</relationshipLabel>
        <relationshipName>Clan_Member_Sessions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Player__c</fullName>
        <label>Player</label>
        <referenceTo>Player__c</referenceTo>
        <relationshipLabel>Clan Member Sessions</relationshipLabel>
        <relationshipName>Clan_Member_Sessions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Clan Member Session</label>
    <nameField>
        <displayFormat>CMS-{000000}</displayFormat>
        <label>Clan Member Session Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clan Member Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Player__c.object
<CustomObject>
    <fields>
        <fullName>Current_Clan_Member_Session__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Current Clan Session</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>This Clan session does not belong to this player</errorMessage>
            <filterItems>
                <field>Clan_Member_Session__c.Player__r.Id</field>
                <operation>equals</operation>
                <valueField>$Source.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Clan_Member_Session__c</referenceTo>
        <relationshipLabel>Players</relationshipLabel>
        <relationshipName>Players</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>32</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Clan_Games_Points__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Clan Games Points</label>
        <precision>8</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Player</label>
    <nameField>
        <label>Player Tag</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PlayerCollectionsHelper.cls
public class PlayerCollectionsHelper {
    
    public static Map<id, Player__c> MapPlayersById(List<Player__c> players){
        return new Map<id, Player__c>(players);
    }
    
    public static Map<String, Player__c> MapPlayersByTag(List<Player__c> players){
        Map<String, Player__c> playerMap = new Map<String, Player__c>();
        for (Player__c player : players){
            playerMap.put(player.name, player);
        }
        return playerMap;
    }
    
    public static Map<String, Player__c> MapPlayersByName(List<Player__c> players){
        Map<String, Player__c> playerMap = new Map<String, Player__c>();
        for (Player__c player : players){
            playerMap.put(player.name__c, player);
        }
        return playerMap;
    }
    
    public static Map<String, Clan_Game_Contribution__c> MapContributionsByPlayerTag(List<Player__c> players, List<Clan_Game_Contribution__c> contributions){
        Map<Id, Player__c> playersById = new Map<Id, Player__c>([SELECT Id, name, Name__c FROM player__c]);

        Map<String, Clan_Game_Contribution__c> contributionsByPlayerTag = new Map<String, Clan_Game_Contribution__c>();
        for(Clan_Game_Contribution__c contribution : contributions){
            contributionsByPlayerTag.put(playersById.get(contribution.player__c).name, contribution);
        }
        return contributionsByPlayerTag;
    }
    
    public static Map<Id, Player__c> getExistingPlayersFrom(List<Player__c> players){
    	Map<id, Player__c> existingPlayers = new Map<id, Player__c>();
        for(Player__c player : players){
            if (player.id != null){
                existingPlayers.put(player.id, player);
            }
        }
        return existingPlayers;
    }
    
    public static List<Player__c> getNewPlayersFrom(List<Player__c> players){
        List<Player__c> newPlayers = new List<Player__c>();
        for(Player__c player : players){
            if (player.id == null){
                newPlayers.add(player.clone());
            }
        }
        return newPlayers;
    }
    
    public static List<Player__c> FindClanPlayerInfo(String clanTag){
        return [
            SELECT Id, Name, Name__c, Current_Clan_Member_Session__c, Total_Clan_Games_Points__c 
            FROM Player__c 
            WHERE Current_Clan_Member_Session__r.Clan__r.Name = :clanTag
        ];
    }
    
}